apiVersion: v1
kind: Service
metadata:
  name: user-auth-service
  labels:
    run: user-auth
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30287
    protocol: TCP
  selector:
    app: user-auth
