apiVersion: v1
kind: Service
metadata:
  name: vm-service
  labels:
    run: vm-service
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30286
    protocol: TCP
  selector:
    app: vm-service
